"""remove skipped column from SurveysAnswers

Revision ID: 1633f7d2bb19
Revises: 97584a3ad4d4
Create Date: 2026-05-23 17:19:42.041287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1633f7d2bb19'
down_revision: Union[str, Sequence[str], None] = '97584a3ad4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SurveysAnswers', 'skipped')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurveysAnswers', sa.Column('skipped', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
