"""add questions_validators_types

Revision ID: 22857ebf9901
Revises: 6c81be4ebe1b
Create Date: 2026-05-30 14:00:55.470396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22857ebf9901'
down_revision: Union[str, Sequence[str], None] = '6c81be4ebe1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionsValidatorsTypes',
    sa.Column('validator_type_id', sa.Integer(), nullable=False),
    sa.Column('validator_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('validator_type_id'),
    sa.UniqueConstraint('validator_type_name')
    )
    
    op.execute("INSERT INTO \"QuestionsValidatorsTypes\" (validator_type_id, validator_type_name) VALUES (1, 'Пустой валидатор')")

    op.add_column('Questions', sa.Column('validator_type_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'Questions', 'QuestionsValidatorsTypes', ['validator_type_id'], ['validator_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Questions', type_='foreignkey')
    op.drop_column('Questions', 'validator_type_id')
    op.drop_table('QuestionsValidatorsTypes')
    # ### end Alembic commands ###
