"""add hashed_password to users

Revision ID: 3863d773eb75
Revises: 5000bfbe0f9f
Create Date: 2026-04-30 17:17:09.292109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3863d773eb75'
down_revision: Union[str, Sequence[str], None] = '5000bfbe0f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'hashed_password')
    # ### end Alembic commands ###
