"""add QuestionsTypes and questions_type_id to Questions

Revision ID: 44de0ef734e2
Revises: 1633f7d2bb19
Create Date: 2026-05-25 16:50:19.694717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44de0ef734e2'
down_revision: Union[str, Sequence[str], None] = '1633f7d2bb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionsTypes',
    sa.Column('questions_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questions_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('questions_type_id'),
    sa.UniqueConstraint('questions_type_name')
    )
    
    op.execute("INSERT INTO \"QuestionsTypes\" (questions_type_id, questions_type_name) VALUES (1, 'Q05'), (2, 'Q38'), (3, 'Q15')")

    op.add_column('Questions', sa.Column('questions_type_id', sa.Integer(), nullable=False, server_default='2'))
    op.create_foreign_key(None, 'Questions', 'QuestionsTypes', ['questions_type_id'], ['questions_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Questions', type_='foreignkey')
    op.drop_column('Questions', 'questions_type_id')
    op.drop_table('QuestionsTypes')
    # ### end Alembic commands ###
