"""initial

Revision ID: 5000bfbe0f9f
Revises: 
Create Date: 2026-04-29 12:29:16.520519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5000bfbe0f9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EducationTypes',
    sa.Column('education_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('education_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('education_type_id'),
    sa.UniqueConstraint('education_type_name')
    )
    op.create_table('Questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('Surveys',
    sa.Column('survey_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_state', sa.String(length=32), nullable=False),
    sa.Column('survey_start_date', sa.DateTime(), nullable=False),
    sa.Column('survey_finish_date', sa.DateTime(), nullable=True),
    sa.Column('survey_conclusion', sa.Text(), nullable=True),
    sa.Column('fact_salary_level', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('desired_salary_level', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('able_salary_level', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('decent_salary_level', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dreams', sa.Text(), nullable=True),
    sa.Column('dreams_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_table('SystemPromptsTypes',
    sa.Column('prompt_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('prompt_type_id'),
    sa.UniqueConstraint('prompt_name')
    )
    op.create_table('TypesOfThinking',
    sa.Column('types_of_thinking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('types_of_thinking_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('types_of_thinking_id'),
    sa.UniqueConstraint('types_of_thinking_name')
    )
    op.create_table('SurveysTypesOfThinking',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('types_of_thinking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['Surveys.survey_id'], ),
    sa.ForeignKeyConstraint(['types_of_thinking_id'], ['TypesOfThinking.types_of_thinking_id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'types_of_thinking_id')
    )
    op.create_table('SystemPrompts',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_type_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_type_id'], ['SystemPromptsTypes.prompt_type_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('married', sa.Boolean(), nullable=True),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['EducationTypes.education_type_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['Surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram')
    )
    op.create_table('UsersAnswers',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['Questions.question_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['Surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'question_id')
    )
    op.create_table('SurveyPrompts',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['SystemPrompts.prompt_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['Surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'prompt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SurveyPrompts')
    op.drop_table('UsersAnswers')
    op.drop_table('Users')
    op.drop_table('SystemPrompts')
    op.drop_table('SurveysTypesOfThinking')
    op.drop_table('TypesOfThinking')
    op.drop_table('SystemPromptsTypes')
    op.drop_table('Surveys')
    op.drop_table('Questions')
    op.drop_table('EducationTypes')
    # ### end Alembic commands ###
