"""add new fields to Questions

Revision ID: 6366e08f46a7
Revises: c03d129033b8
Create Date: 2026-05-07 12:22:56.737202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6366e08f46a7'
down_revision: Union[str, Sequence[str], None] = 'c03d129033b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('type_of_thinking', sa.Integer(), nullable=False))
    op.add_column('Questions', sa.Column('focus', sa.Text(), nullable=False))
    op.add_column('Questions', sa.Column('clarification_1', sa.Text(), nullable=False))
    op.add_column('Questions', sa.Column('clarification_2', sa.Text(), nullable=False))
    op.add_column('Questions', sa.Column('key_indicators', sa.Text(), nullable=False))
    op.add_column('Questions', sa.Column('proof', sa.Text(), nullable=False))
    op.add_column('Questions', sa.Column('interpretation_template', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'Questions', 'TypesOfThinking', ['type_of_thinking'], ['types_of_thinking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Questions', type_='foreignkey')
    op.drop_column('Questions', 'interpretation_template')
    op.drop_column('Questions', 'proof')
    op.drop_column('Questions', 'key_indicators')
    op.drop_column('Questions', 'clarification_2')
    op.drop_column('Questions', 'clarification_1')
    op.drop_column('Questions', 'focus')
    op.drop_column('Questions', 'type_of_thinking')
    # ### end Alembic commands ###
