"""add partial unique index for sort_order=1

Revision ID: 6bdf7c3d023e
Revises: 25222d9a21ea
Create Date: 2026-06-01 14:14:00.131076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdf7c3d023e'
down_revision: Union[str, Sequence[str], None] = '25222d9a21ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_questions_active_type_sort',
        'Questions',
        ['questions_type_id', 'sort_order'],
        unique=True,
        postgresql_where=sa.text('active = true')  # или 'active = 1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_questions_active_type_sort', table_name='Questions')
    # ### end Alembic commands ###
