"""add surveys_states and dialogs

Revision ID: 6c81be4ebe1b
Revises: 63e4b3b62041
Create Date: 2026-05-29 17:43:29.133112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c81be4ebe1b'
down_revision: Union[str, Sequence[str], None] = '63e4b3b62041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SurveysStates',
    sa.Column('survey_state_id', sa.Integer(), nullable=False),
    sa.Column('survey_state_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('survey_state_id'),
    sa.UniqueConstraint('survey_state_name')
    )

    states = [
        {'survey_state_id': 1, 'survey_state_name': 'CREATED'},
        {'survey_state_id': 2, 'survey_state_name': 'Q05_IN_PROGRESS'},
        {'survey_state_id': 3, 'survey_state_name': 'Q05_COMPLETED'},
        {'survey_state_id': 4, 'survey_state_name': 'Q05_ANALYZED'},
        {'survey_state_id': 5, 'survey_state_name': 'Q38_IN_PROGRESS'},
        {'survey_state_id': 6, 'survey_state_name': 'Q38_COMPLETED'},
        {'survey_state_id': 7, 'survey_state_name': 'Q38_ANALYZED'},
        {'survey_state_id': 8, 'survey_state_name': 'Q15_IN_PROGRESS'},
        {'survey_state_id': 9, 'survey_state_name': 'Q15_COMPLETED'},
        {'survey_state_id': 10, 'survey_state_name': 'Q15_ANALYZED'},
        {'survey_state_id': 11, 'survey_state_name': 'COMPLETED'},
    ]

    op.bulk_insert(
        sa.table('SurveysStates',
            sa.column('survey_state_id', sa.Integer),
            sa.column('survey_state_name', sa.String)
        ),
        states
    )
    
    op.create_table('SurveysAnswersDialogs',
    sa.Column('dialog_pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('dialog_pair_question', sa.Text(), nullable=False),
    sa.Column('dialog_pair_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id', 'question_id'], ['SurveysAnswers.survey_id', 'SurveysAnswers.question_id'], ),
    sa.PrimaryKeyConstraint('dialog_pair_id')
    )
    op.add_column('Surveys', sa.Column('survey_state_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_foreign_key(None, 'Surveys', 'SurveysStates', ['survey_state_id'], ['survey_state_id'])
    op.drop_column('Surveys', 'survey_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Surveys', sa.Column('survey_state', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Surveys', type_='foreignkey')
    op.drop_column('Surveys', 'survey_state_id')
    op.drop_table('SurveysAnswersDialogs')
    op.drop_table('SurveysStates')
    # ### end Alembic commands ###
