"""make telegram fields not nullable

Revision ID: 759c11b8b97a
Revises: fecfe3884009
Create Date: 2026-05-12 20:46:30.527035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759c11b8b97a'
down_revision: Union[str, Sequence[str], None] = 'fecfe3884009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'telegram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('Users', 'telegram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
