"""add SurveysAnswersStates and update UserAnswer

Revision ID: 97584a3ad4d4
Revises: f5d9d9e0480f
Create Date: 2026-05-23 13:35:18.765013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97584a3ad4d4'
down_revision: Union[str, Sequence[str], None] = 'f5d9d9e0480f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Описываем временную таблицу для bulk_insert
SurveysAnswersStates_table = sa.table(
    'SurveysAnswersStates',
    sa.column('answer_state_id', sa.Integer),
    sa.column('answer_state_name', sa.String)
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SurveysAnswersStates',
    sa.Column('answer_state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_state_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('answer_state_id'),
    sa.UniqueConstraint('answer_state_name')
    )
    # 2. Вставляем начальные данные
    op.bulk_insert(
        SurveysAnswersStates_table,
        [
            {'answer_state_id': 1, 'answer_state_name': 'ПОДГОТОВЛЕН'},
            {'answer_state_id': 2, 'answer_state_name': 'ПРОПУЩЕН'},
            {'answer_state_id': 3, 'answer_state_name': 'ЗАВЕРШЁН'},
        ]
    )
    op.add_column('SurveysAnswers', sa.Column('answer_state_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('SurveysAnswers', sa.Column('skipped', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('SurveysAnswers', sa.Column('reformulated_text', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'SurveysAnswers', 'SurveysAnswersStates', ['answer_state_id'], ['answer_state_id'])

    # Явно обновляем существующие записи (если требуется)
    op.execute("UPDATE \"SurveysAnswers\" SET answer_state_id = 1 WHERE answer_state_id IS NULL")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SurveysAnswers', type_='foreignkey')
    op.drop_column('SurveysAnswers', 'reformulated_text')
    op.drop_column('SurveysAnswers', 'skipped')
    op.drop_column('SurveysAnswers', 'answer_state_id')
    op.drop_table('SurveysAnswersStates')
    # ### end Alembic commands ###
