"""Update User Model: add conclusion fields

Revision ID: c78a0eeaafd4
Revises: 09b5a0119121
Create Date: 2026-05-14 19:37:05.737457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78a0eeaafd4'
down_revision: Union[str, Sequence[str], None] = '09b5a0119121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Surveys', sa.Column('survey_conclusion_q05', sa.Text(), nullable=True))
    op.add_column('Surveys', sa.Column('survey_conclusion_q38', sa.Text(), nullable=True))
    op.add_column('Surveys', sa.Column('survey_conclusion_val', sa.Text(), nullable=True))
    op.drop_column('Surveys', 'survey_conclusion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Surveys', sa.Column('survey_conclusion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('Surveys', 'survey_conclusion_val')
    op.drop_column('Surveys', 'survey_conclusion_q38')
    op.drop_column('Surveys', 'survey_conclusion_q05')
    # ### end Alembic commands ###
