"""add roles tables

Revision ID: c8585c75a9dd
Revises: ca0461caaea5
Create Date: 2026-04-30 19:36:10.662791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8585c75a9dd'
down_revision: Union[str, Sequence[str], None] = 'ca0461caaea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('UsersRoles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###
    
    # Заполнение начальных ролей
    op.execute('INSERT INTO "Roles" (role_id, role_name) VALUES ' +
        "(1, 'Испытуемый'), (2, 'Специалист'), (3, 'Admin')")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersRoles')
    op.drop_table('Roles')
    # ### end Alembic commands ###
