"""dream point set text

Revision ID: f5d9d9e0480f
Revises: 490c98e3292c
Create Date: 2026-05-20 17:07:57.594082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d9d9e0480f'
down_revision: Union[str, Sequence[str], None] = '490c98e3292c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Surveys', 'dreams_point',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Surveys', 'dreams_point',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
