"""make first_name, last_name, date_of_birth, gender optional

Revision ID: f6b0bcb5cdc2
Revises: 0c7be6a88da9
Create Date: 2026-05-07 14:46:11.754965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b0bcb5cdc2'
down_revision: Union[str, Sequence[str], None] = '0c7be6a88da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Users', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('Users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
