"""Seed Prompts Types

Revision ID: fecfe3884009
Revises: 9fc21e6d9b74
Create Date: 2026-05-12 20:28:39.331602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecfe3884009'
down_revision: Union[str, Sequence[str], None] = '9fc21e6d9b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('INSERT INTO "SystemPromptsTypes" (prompt_name) VALUES ' +
        "('AQ5'), ('AQ38'), ('EST')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "SystemPromptsTypes"')
    # ### end Alembic commands ###
